---
title: "Unidad de Estadística - PPP"
author: "Chullo Puclla Oscar"
institute: "Universidad Nacional de San Antonio Abad del Cusco"
format: 
  revealjs:
    theme: beige
editor: visual
logo: imagen/unsaac.png
footer: "Prácticas Pre-Profesionales"
---

## Introducción

Las prácticas pre-profesionales nos permiten integrar los conocimientos y habilidades adquiridas en la formación académica, puesto que estas constituyen una fase clave en el desarrollo profesional. En este contexto, se ha tenido la oportunidad de realizar Prácticas Pre-Profesionales (PPP) en la Universidad Nacional de San Antonio Abad del Cusco, en particular en la Unidad de Estadística.

## Unidad de Estadística

La Unidad de Estadística es una Unidad Orgánica comprendida dentro de la organización de la Direccion de Sistemas de Informacion, tiene a su cargo la recopilación, sistematización, análisis y publicación de los datos estadísticos necesarios para la planificación y programación de las actividades que desarrolla la universidad, realiza estudios y diagnósticos sociales, económicos  y académicos.

## Funciones

- Ejecutar las actividades estadísticas de acuerdo a los requerimientos institucionales.
- Capturar, elaborar, revisar, criticar validar y procesar para su difusión, las estadísticas a fin de facilitar la gestión y toma de decisiones.
- Suministrar datos estadísticos solicitados por las diferentes dependencias del Nivel Nacional, Regional, Local e institucional.
- Realizar estudios estadísticos sobre aspectos diversos de la problemática universitaria que permita un mejor conocimiento de la realidad.

------------------------------------------------------------------------

- Elaborar indicadores e índices económicos y sociales para el análisis y formulación de políticas institucionales.
- Establecer métodos para el cálculo de tendencias y/o proyecciones estadísticas.
- Realizar diagnósticos sociales económicos y académicos de la Universidad.
- Publicar anualmente boletines estadísticos, trípticos y otros documentos.
- Organizar y administrar el banco de datos estadísticos de la institución.

## Organización

1. **Órgano de Dirección:** "Unidad de Estadística"
- **Órganos de Línea:** "Unidad de Recopilación, procesamiento y análisis estadístico" y "Unidad de Estudios socio económicos"

2. **Personal del Área:** 
- **Jefe de la Unidad de Estadística:**  Econ CARLOS HUAMAN AGUILAR
- **correo electrónico:** estadistica@unsaac.edu.pe

----------------------------------------------------------------

### Misión
Producir y difundir las estadísticas de la UNSAAC con calidad y transparencia para la toma de decisiones en materia académica, administrativa y política institucional.

### Visión
Ser reconocida, como la fuente fundamental de las estadísticas de la UNSAAC por la calidad en sus productos y servicios ofrecidos a los demandantes.
